services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_leme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SUA_SENHA_AQUI
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
